=== Kemp-J/DFCData/Schemas/fleet/hero.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://dfc/schemas/fleet/hero.json",
    "title": "DFC Hero Ship Data",
    "description": "Data file for a Hero ship.",
    "type": "object",
    "required": [
        "Hero",
        "Ship",
        "Type",
        "Points",
        "Tonnage",
        "BaseSize",
        "Profile",
        "Weapons",
        "Load",
        "KnownShips",
        "Flavour"
    ],
    "additionalProperties": false,
    "properties": {
        "Hero":              { "type": "string" },
        "Ship":              { "type": "string" },
        "Type":              { "type": "string" },
        "Points":            { "type": "integer" },
        "Tonnage":           { "$ref": "https://dfc/schemas/defs.json#/$defs/Tonnage" },
        "BaseSize":          { "type": "integer" },
        "Profile":           { "$ref": "https://dfc/schemas/defs.json#/$defs/ShipProfile" },
        "Weapons":           { "type": "array", "items": { "$ref": "https://dfc/schemas/defs.json#/$defs/Weapon" } },
        "Load":              { "type": "array", "items": { "$ref": "https://dfc/schemas/defs.json#/$defs/LoadEntry" } },
        "Upgrades":          { "type": "array", "items": { "$ref": "https://dfc/schemas/defs.json#/$defs/UpgradeEntry" } },
        "Rules":             { "type": "array", "items": { "$ref": "https://dfc/schemas/defs.json#/$defs/Rule" } },
        "AdmiralAbilities":  { "type": "array", "items": { "$ref": "https://dfc/schemas/defs.json#/$defs/Ability" } },
        "UsableIn":          { "type": "array", "items": { "$ref": "https://dfc/schemas/defs.json#/$defs/UsableInEntry" } },
        "KnownShips":        { "type": "array", "items": { "type": "string" } },
        "Flavour":           { "type": "string" }
    }
}

=== Kemp-J/DFCData/Data/PHR/avram_bei.json
{
    "Hero": "Avram Bei",
    "Ship": "Subatomic",
    "Type": "Heavy Destroyer",
    "Points": 96,
    "Tonnage": "L",
    "BaseSize": 30,
    "Profile": {
        "Thrust": 12,
        "Scan": 8,
        "Sig": 2,
        "Hull": 8,
        "ES": "4+",
        "KS": "5+",
        "BS": "6+",
        "G": "1",
        "Special": [
            "Hero",
            "Unique"
        ]
    },
    "Weapons": [
        {
            "Name": "Neutron Missile Silo",
            "Arc": "F/S",
            "Att": 3,
            "Lock": "2+",
            "DMG": 2,
            "Type": "E",
            "Special": [
                "Close Action",
                "Crippling",
                "Penetrator"
            ]
        },
        {
            "Name": "Twin Supernova Laser",
            "Arc": "FN",
            "Att": 3,
            "Lock": "3+",
            "DMG": 2,
            "Type": "E",
            "Special": [
                "Burnthrough-2",
                "Flash-2",
                "Focused"
            ]
        }
    ],
    "Load": [],
    "KnownShips": [
        "Subatomic"
    ],
    "Flavour": "Neutron missiles are a rightly feared branch of PHR weapons technology, but until now they have been confined to the largest capital ships due to warhead core containment requirements prior to launch. A single new ship, Subatomic, has a full battery of these top-tier munitions though, complimented with twinned lasers, despite its slightly enlarged destroyer tonnage. It's understood that this ship has yet to receive clearance for wider construction. Possible crew losses due to containment failures have been rumoured although secrecy surrounds the vessel.\nIts famous captain, Avram Bei, is part of a splinter fleet that has yet to declare for one side or the other in the PHR's recent schism, preferring to focus on their bloody pursuit of Shaltari pirates near Aaru before considering theological matters, or whether theology is even the right way of thinking about the White Sphere. Bei is a practical, non-nonsense warrior with little interest in the big picture. He is known to relish fighting at the heart of any engagement, a joy undimmed even though half of his frequently injured body has been replaced with combat augmetics."
}

=== Kemp-J/DFCData/Data/UCM/rhiannon_major.json
{
    "Hero": "Rhiannon Major",
    "Ship": "Leaden Triad",
    "Type": "Heavy Destroyer",
    "Points": 71,
    "Tonnage": "L",
    "BaseSize": 30,
    "Profile": {
        "Thrust": 8,
        "Scan": 6,
        "Sig": 4,
        "Hull": 6,
        "ES": "3+",
        "KS": "4+",
        "BS": "6+",
        "G": "1",
        "Special": [
            "Hero",
            "Unique"
        ]
    },
    "Weapons": [
        {
            "Name": "Artillery Cannon",
            "Arc": "F",
            "Att": 1,
            "Lock": "4+",
            "DMG": 2,
            "Type": "K",
            "Special": [
                "Calibre-H/C",
                "Fusillade-1",
                "Low Power"
            ]
        },
        {
            "Name": "Artillery Cannon",
            "Arc": "F",
            "Att": 1,
            "Lock": "4+",
            "DMG": 2,
            "Type": "K",
            "Special": [
                "Calibre-H/C",
                "Fusillade-1",
                "Low Power"
            ]
        },
        {
            "Name": "Artillery Cannon",
            "Arc": "F",
            "Att": 1,
            "Lock": "4+",
            "DMG": 2,
            "Type": "K",
            "Special": [
                "Calibre-H/C",
                "Fusillade-1",
                "Low Power"
            ]
        }
    ],
    "Load": [],
    "KnownShips": [
        "- Leaden Triad"
    ],
    "Flavour": "Leaden Triad is a new, experimental vessel designed and built by the restored Eden Drive Yards Corporation. This pre-war colossus was ended by the Scourge invasion, but this reincarnation is based in its recaptured shipyards, and the new corporation has all the recovered tech of its predecessor, including its work on the largest chemical guns ever built. Though they never got a chance to enter service, three prototypes were recovered and have been installed aboard a unique heavy destroyer hull.\nCaptain Rhiannon Major, already the UCM's finest naval gunnery officer at just 34 years of age, has been given command. Though not a natural leader, her icy bravery and uncanny intelligence are the natural fit to shepherd this project into combat testing. Already, she has demonstrated the devastating power of this antique technology when writ large by deftly annihilating two Bioficer battlecruisers. These guns hurl house-sized shells at vast muzzle energy with negligible power drain, allowing full manoeuvrability and systems use while firing weapons far exceeding this ship's tonnage grade. However, despite Major's calculations and brilliant heat management, frequent and ultra-costly barrel changes seem inevitable."
}

=== Kemp-J/DFCData/Data/Bioficer/anode.json
{
    "Hero": "Anode",
    "Ship": "The Melter",
    "Type": "Heavy Destroyer",
    "Points": 93,
    "Tonnage": "L",
    "BaseSize": 40,
    "Profile": {
        "Thrust": 8,
        "Scan": 8,
        "Sig": 2,
        "Hull": 7,
        "ES": "4+",
        "KS": "4+",
        "BS": "5+",
        "G": "1",
        "Special": [
            "Hero",
            "Unique"
        ]
    },
    "Weapons": [
        {
            "Name": "Thermator Cage",
            "Profiles": [
                {
                    "Name": "Long Range",
                    "Arc": "FN",
                    "Att": 4,
                    "Lock": "4+",
                    "DMG": 2,
                    "Type": "E",
                    "Special": [
                        "Alt-1",
                        "Overcharge",
                        "Scald-2"
                    ]
                },
                {
                    "Name": "Short Range",
                    "Arc": "FN",
                    "Att": 4,
                    "Lock": "3+",
                    "DMG": 2,
                    "Type": "E",
                    "Special": [
                        "Alt-1",
                        "Close Action",
                        "Overcharge",
                        "Scald-3"
                    ]
                }
            ]
        }
    ],
    "Load": [],
    "KnownShips": [
        "The Melter"
    ],
    "Flavour": "Nicknamed by lucky survivors, The Melter became a feared lone wolf among Bioficer raiding parties. Its favoured victims were larger foes who didn't feel as threatened by a vessel of its modest size as they should. No other ship was known in this configuration, so the Admiralty assigned its guiding Intelligence the designation Anode. This individual was entirely unsubtle and clearly had access to superior technology over its peers.\nIt featured an enhanced superstructure and power matrix, upping it to heavy destroyer tonnage. All this supported a single, prow weapons system: the Themator Cage. Quite different in form to regular thermators, this was as devastating as most battleship primary armaments, albeit only at close range. This led to the vessel's destruction at the hands of the UCMS Gaugamela over Olympus in early 2679. However, reports of an identical vessel and characteristic behaviours followed weeks later, forcing the Admiralty to conclude that this Intelligence had successfully transferred out and potentially has several of these unusual vessels at its disposal."
}

=== Kemp-J/DFCData/Data/Shaltari/nefertem_of_the_dawn.json
{
    "Hero": "Nefertem of the Dawn",
    "Ship": "Invisible Night",
    "Type": "Heavy Destroyer",
    "Points": 81,
    "Tonnage": "L",
    "BaseSize": 30,
    "Profile": {
        "Thrust": 12,
        "Scan": 12,
        "Sig": 6,
        "Hull": 7,
        "ES": "5+",
        "KS": "4+",
        "BS": "-",
        "G": "1",
        "Special": [
            "Cloak-2",
            "Hero",
            "Shield-5+",
            "Stealth",
            "Unique"
        ]
    },
    "Weapons": [
        {
            "Name": "Microwave Crescent",
            "Arc": "F",
            "Att": 4,
            "Lock": "3+",
            "DMG": 1,
            "Type": "C",
            "Special": [
                "Crippling-2xFire",
                "Sustained Fire"
            ]
        }
    ],
    "Load": [],
    "KnownShips": [
        "Invisible Night"
    ],
    "Flavour": "Stealth technology and camouflage in all its forms are abhorrent and dishonourable for most Shaltari, but Nefertem chose long ago to reject this notion. Her stance is that subterfuge and surprise attack are time-honoured, central tenets of battle and has chosen to master them. To that end, she commissioned a unique vessel.\nInvisible Light demonstrates that, of course, the Shaltari are perfectly capable of matching or exceeding the Scourge in stealth technology if they so wish. Of heavy destroyer tonnage, this vessel's innocuous-looking additional frontal superstructure arms conceal this cloaking system as well as supporting the additional mass of its only weapons system. The thus-far unique Microwave Crescent is a long range, low-observable variant of typical microwave technology that can reach into the heart of any target, cooking its crew and delicate systems from the inside. Often, the victim has no idea where the burst came from and has little chance of returning fire."
}

=== Kemp-J/DFCData/Data/Resistance/guy_fawkes.json
{
    "Hero": "Guy Fawkes",
    "Ship": "Parliament",
    "Type": "Fire Ship",
    "Points": 85,
    "Tonnage": "L",
    "BaseSize": 40,
    "Profile": {
        "Thrust": 9,
        "Scan": 6,
        "Sig": 4,
        "Hull": 6,
        "ES": "2+",
        "KS": "2+",
        "BS": "6+",
        "G": "1",
        "Special": [
            "Hero",
            "Unique"
        ]
    },
    "Weapons": [
        {
            "Name": "Explosive Detonation",
            "Arc": "F/S/R",
            "Att": 8,
            "Lock": "3+",
            "DMG": 1,
            "Type": "C",
            "Special": [
                "Critical-1"
            ],
            "Rule": "When attacking with this weapon, skip the assign weapons to targets step and proceed to roll to hit instead. When rolling to hit with this weapon, for each result of a 6 (including rolls from this rule), roll an additional dice. After rolling to hit, assign hits as equally as possible to each other Ship and Space Station on the same Orbital Layer within 6\" until no hits remain. Then continue the attack sequence as normal."
        }
    ],
    "Load": [],
    "Rules": [
        {
            "Name": "Set Timers And Run",
            "Text": "Once you complete an attack sequence with Explosive Detonation, remove this ship from the game. If there is a friendly Ship within 8\" of this Ship, place a Fawkes' Crew Battalion on that Ship. This ship only counts for Ships killed when Fawkes' Crew Battalion is removed from the game."
        },
        {
            "Name": "Skeleton Crew",
            "Text": "This Ship can only go on General Quarters."
        }
    ],
    "KnownShips": [
        "Parliament (and its many successors)"
    ],
    "Flavour": "Guy Fawkes, clearly not his real name, is infamous for one thing—blowing battleships to smithereens with massive fire ships, laughing. His small, eager crew of plastique-happy privateers are backed by a personal deep space shipyard kitted out for packing ships with explosives and up-armouring them enough to survive a one-way charge towards any enemy of any sufficiently flushed benefactor. Fawkes prefers old colony ships as candidates given their cavernous holds. To their creaking frames his engineers affix laughably thick frontal armour plates, having freed up mass by tearing out crew quarters, weapons, spares, and anything needed for long-term operations.\nIn combat, Fawkes flies his ship-sized munition personally alongside an insanely loyal, or just insane, skeleton crew. They all jump ship in escape pods at the last possible moment, coordinating with a nearby friendly vessel to collect them so they might do it all again another day. He's currently on Parliament XIII with no indication he might retire for the quiet life among his explosively gotten gains."
}
